# -*- coding: utf-8 -*-
"""Análisis estructural de vigas contínuas mendiante el médodo de rigidez.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1az04Q_Vnqq6Jx38ebSmtl5wmOda7olXw
"""

import numpy as np
import matplotlib.pyplot as plt

def analizar_viga_final(longitudes, cargas_w, E, I):
    if len(longitudes) != len(cargas_w):
        print("⚠️⚠️⚠️Las listas de tramos y cargas deben tener el mismo tamaño.⚠️⚠️⚠️")
        return None
    else:
        n_tramos = len(longitudes)
        n_nudos = n_tramos + 1
        n_gdl = n_nudos * 2
        K_global = np.zeros((n_gdl, n_gdl))
        F_global = np.zeros(n_gdl)

        # 1. Ensamblaje de Matriz Global y Vector de Cargas
        for i in range(n_tramos):
            L, w = longitudes[i], cargas_w[i]
            k_local = (E * I / L**3) * np.array([
                [12, 6*L, -12, 6*L], [6*L, 4*L**2, -6*L, 2*L**2],
                [-12, -6*L, 12, -6*L], [6*L, 2*L**2, -6*L, 4*L**2]
            ])
            v_emp, m_emp = w * L / 2, w * L**2 / 12
            f_local_emp = np.array([-v_emp, -m_emp, -v_emp, m_emp])
            idx = [2*i, 2*i+1, 2*i+2, 2*i+3]
            for r in range(4):
                for c in range(4):
                    K_global[idx[r], idx[c]] += k_local[r, c]
                F_global[idx[r]] += f_local_emp[r]

        # 2. Condiciones de Contorno y Solución
        gdl_restringidos = [2*i for i in range(n_nudos)]
        gdl_libres = [i for i in range(n_gdl) if i not in gdl_restringidos]
        K_red = K_global[np.ix_(gdl_libres, gdl_libres)]
        F_red = F_global[gdl_libres]
        giros = np.linalg.solve(K_red, F_red)

        U = np.zeros(n_gdl)
        U[gdl_libres] = giros
        reacciones = np.dot(K_global, U) - F_global

        # 3. Discretización para Diagramas
        x_total, V_total, M_total, Def_total = [], [], [], []
        tramos_data = []
        x_acumulado = 0

        for i in range(n_tramos):
            L, w = longitudes[i], cargas_w[i]
            u_elem = U[2*i: 2*i+4]
            k_local_i = (E * I / L**3) * np.array([
                [12, 6*L, -12, 6*L], [6*L, 4*L**2, -6*L, 2*L**2],
                [-12, -6*L, 12, -6*L], [6*L, 2*L**2, -6*L, 4*L**2]
            ])
            f_emp_local = np.array([w*L/2, w*L**2/12, w*L/2, -w*L**2/12])
            f_internas = np.dot(k_local_i, u_elem) + f_emp_local

            V_izq = f_internas[0]
            M_izq = -f_internas[1]

            puntos_x = np.linspace(0, L, 200)
            x_tramo, V_tramo, M_tramo, Def_tramo = [], [], [], []

            for px in puntos_x:
                Vx = V_izq - w * px
                Mx = M_izq + V_izq * px - 0.5 * w * px**2
                N = np.array([1-3*(px/L)**2+2*(px/L)**3, px*(1-px/L)**2,
                              3*(px/L)**2-2*(px/L)**3, px*((px/L)**2-px/L)])
                y_def = np.dot(N, u_elem) - (w*px**2 * (L-px)**2)/(24*E*I)

                x_tramo.append(px + x_acumulado)
                V_tramo.append(Vx)
                M_tramo.append(Mx)
                Def_tramo.append(y_def)

            x_total.extend(x_tramo)
            V_total.extend(V_tramo)
            M_total.extend(M_tramo)
            Def_total.extend(Def_tramo)

            tramos_data.append({
                'x': x_tramo, 'V': V_tramo, 'M': M_tramo, 'Def': Def_tramo,
                'x_ini': x_acumulado, 'x_fin': x_acumulado + L,
                'x_mid': x_acumulado + L / 2, 'L': L, 'w': w,
            })
            x_acumulado += L

        posiciones_apoyos = [0] + list(np.cumsum(longitudes))
        L_total = posiciones_apoyos[-1]

        return {
            'posiciones_apoyos': posiciones_apoyos,
            'L_total': L_total,
            'reacciones': reacciones,
            'tramos_data': tramos_data,
            'x_total': x_total,
            'V_total': V_total,
            'M_total': M_total,
            'Def_total': Def_total,
        }

def plot_beam_results(posiciones_apoyos, L_total, reacciones, tramos_data, x_total, V_total, M_total, Def_total):
    # ── Helper: anotar un punto ────────────────────────────────────────────────
    def anotar(ax, x, y, label, color, offset_y=12, offset_x=0, fontsize=7.5):
        ax.annotate(
            label, xy=(x, y), xytext=(offset_x, offset_y),
            textcoords='offset points', ha='center', va='bottom',
            fontsize=fontsize, color=color, fontweight='bold',
            arrowprops=dict(arrowstyle='->', color=color, lw=0.8),
        )

    # ── Helper: cruces de V con cero ──────────────────────────────────────────
    def x_V_cero(td):
        V = np.array(td['V'])
        x = np.array(td['x'])
        crosses = np.where(np.diff(np.sign(V)))[0]
        results = []
        for c in crosses:
            x0, x1, v0, v1 = x[c], x[c+1], V[c], V[c+1]
            xz = x0 - v0 * (x1 - x0) / (v1 - v0)
            idx = np.argmin(np.abs(x - xz))
            results.append((xz, td['M'][idx]))
        return results

    # ══════════════════════════════════════════════════════════════════════════
    # FIGURA: 5 subplots
    # ══════════════════════════════════════════════════════════════════════════
    fig = plt.figure(figsize=(13, 21))
    gs = fig.add_gridspec(5, 1, height_ratios=[2.4, 1.1, 1.4, 1.4, 1.4],
                          hspace=0.60)
    ax_viga = fig.add_subplot(gs[0])
    ax_reac = fig.add_subplot(gs[1])
    ax_V    = fig.add_subplot(gs[2], sharex=ax_reac)
    ax_M    = fig.add_subplot(gs[3], sharex=ax_reac)
    ax_Def  = fig.add_subplot(gs[4], sharex=ax_reac)

    fig.suptitle("ANÁLISIS ESTRUCTURAL DE VIGAS CONTÍNUAS   |  Autor: Mario Cesgo S.", fontsize=14,
                fontweight='bold', y=0.998)

    # ══════════════════════════════════════════════════════════════════════════
    # SUBPLOT 1 — ESQUEMA DE LA VIGA
    # ══════════════════════════════════════════════════════════════════════════
    ax_viga.set_xlim(-0.4, L_total + 0.4)
    ax_viga.set_ylim(-0.28, 0.62)
    ax_viga.axis('off')
    ax_viga.set_title("Esquema de la Viga", fontsize=10, fontweight='bold', pad=4)

    # Línea de la viga
    ax_viga.plot([0, L_total], [0, 0], color='saddlebrown', lw=6, zorder=3,
                solid_capstyle='butt')

    # Apoyos
    for loc in posiciones_apoyos:
        ax_viga.plot(loc, 0, '^', color='dimgray', markersize=15, zorder=4,
                    markeredgecolor='black', markeredgewidth=0.8)
        ax_viga.plot([loc - 0.18, loc + 0.18], [-0.045, -0.045],
                    color='dimgray', lw=2.5)

    # Cargas distribuidas + cotas
    arrow_top = 0.44
    arrow_bot = 0.05
    n_flechas = 7

    for td in tramos_data:
        x_ini, x_fin = td['x_ini'], td['x_fin']
        w_kNm = td['w'] / 1000

        # Línea superior de la carga
        ax_viga.plot([x_ini, x_fin], [arrow_top, arrow_top],
                    color='steelblue', lw=2.2)

        # Flechas verticales de carga
        for xf in np.linspace(x_ini, x_fin, n_flechas):
            ax_viga.annotate(
                '', xy=(xf, arrow_bot), xytext=(xf, arrow_top),
                arrowprops=dict(arrowstyle='->', color='steelblue',
                                lw=1.4, mutation_scale=11)
            )

        # Etiqueta de carga
        ax_viga.text(td['x_mid'], arrow_top + 0.045,
                    f'w = {w_kNm:.1f} kN/m',
                    ha='center', va='bottom', fontsize=9.5,
                    color='steelblue', fontweight='bold')

        # ── Cota de longitud (debajo de la viga) ──
        y_cota = -0.13
        y_tick = -0.10
        # Ticks verticales
        for xc in [x_ini, x_fin]:
            ax_viga.plot([xc, xc], [y_tick, y_cota],
                        color='black', lw=1.2)
        # Flecha doble
        ax_viga.annotate(
            '', xy=(x_fin, y_cota), xytext=(x_ini, y_cota),
            arrowprops=dict(arrowstyle='<->', color='black',
                            lw=1.3, mutation_scale=11)
        )
        ax_viga.text(td['x_mid'], y_cota - 0.045,
                    f'L = {td["L"]:.1f} m',
                    ha='center', va='top', fontsize=9.5,
                    color='black', fontweight='bold')

    # ══════════════════════════════════════════════════════════════════════════
    # SUBPLOT 2 — REACCIONES
    # ══════════════════════════════════════════════════════════════════════════
    ax_reac.axhline(0, color='black', lw=2.5)
    for i, loc in enumerate(posiciones_apoyos):
        ax_reac.plot(loc, 0, '^r', markersize=12, zorder=4)
        R_kN = reacciones[2*i] / 1000
        ax_reac.annotate(
            f'R = {R_kN:.2f} kN',
            (loc, 0), xytext=(0, 17),
            textcoords='offset points', ha='center',
            fontsize=9, fontweight='bold', color='crimson',
            arrowprops=dict(arrowstyle='->', color='crimson', lw=0.8)
        )
    ax_reac.set_title("Reacciones en Apoyos", fontsize=10, fontweight='bold')
    ax_reac.set_yticks([])
    ax_reac.set_ylim(-0.04, 0.065)
    for xv in posiciones_apoyos:
        ax_reac.axvline(xv, color='gray', lw=0.5, ls=':')

    # ══════════════════════════════════════════════════════════════════════════
    # SUBPLOT 3 — CORTANTE
    # ══════════════════════════════════════════════════════════════════════════
    ax_V.axhline(0, color='black', lw=0.8, ls='--')
    ax_V.fill_between(x_total, V_total, color='green', alpha=0.25)
    ax_V.plot(x_total, V_total, 'g', lw=1.5)

    for td in tramos_data:
        V_arr = np.array(td['V'])
        x_arr = np.array(td['x'])
        V_ini, V_fin = V_arr[0], V_arr[-1]

        ax_V.plot(td['x_ini'], V_ini, 'go', ms=4)
        ax_V.plot(td['x_fin'], V_fin, 'go', ms=4)
        anotar(ax_V, td['x_ini'], V_ini, f'{V_ini/1000:.2f} kN', 'darkgreen',
              offset_y=10 if V_ini >= 0 else -14)
        anotar(ax_V, td['x_fin'], V_fin, f'{V_fin/1000:.2f} kN', 'darkgreen',
              offset_y=10 if V_fin >= 0 else -14)

        idx_max = np.argmax(np.abs(V_arr))
        if 0.05 * len(V_arr) < idx_max < 0.95 * len(V_arr):
            V_ext = V_arr[idx_max]
            ax_V.plot(x_arr[idx_max], V_ext, 'g^', ms=5)
            anotar(ax_V, x_arr[idx_max], V_ext, f'{V_ext/1000:.2f} kN', 'green',
                  offset_y=10 if V_ext >= 0 else -14)

        for xv in [td['x_ini'], td['x_fin']]:
            ax_V.axvline(xv, color='gray', lw=0.5, ls=':')
    ax_V.set_title("Diagrama de Fuerza Cortante (V)", fontsize=10, fontweight='bold')
    ax_V.set_ylabel("V (kN)")
    ax_V.yaxis.set_major_formatter(plt.FuncFormatter(lambda v, _: f'{v/1000:.0f}'))
    ax_V.grid(True, alpha=0.4)

    # ══════════════════════════════════════════════════════════════════════════
    # SUBPLOT 4 — MOMENTO
    # ══════════════════════════════════════════════════════════════════════════
    ax_M.axhline(0, color='black', lw=0.8, ls='--')
    ax_M.fill_between(x_total, M_total, color='red', alpha=0.25)
    ax_M.plot(x_total, M_total, 'r', lw=1.5)

    for td in tramos_data:
        M_arr = np.array(td['M'])
        x_arr = np.array(td['x'])
        M_ini, M_fin = M_arr[0], M_arr[-1]

        ax_M.plot(td['x_ini'], M_ini, 'ro', ms=4)
        ax_M.plot(td['x_fin'], M_fin, 'ro', ms=4)
        anotar(ax_M, td['x_ini'], M_ini, f'{M_ini/1000:.2f} kN·m', 'darkred',
              offset_y=-14 if M_ini >= 0 else 10)
        anotar(ax_M, td['x_fin'], M_fin, f'{M_fin/1000:.2f} kN·m', 'darkred',
              offset_y=-14 if M_fin >= 0 else 10)

        for xz, Mz in x_V_cero(td):
            ax_M.plot(xz, Mz, 'r^', ms=6)
            anotar(ax_M, xz, Mz, f'{Mz/1000:.2f} kN·m', 'red',
                  offset_y=-14 if Mz >= 0 else 10)

        idx_max = np.argmax(np.abs(M_arr))
        M_ext = M_arr[idx_max]
        zeros_x = [xz for xz, _ in x_V_cero(td)]
        if (0.05 * len(M_arr) < idx_max < 0.95 * len(M_arr) and
                all(abs(x_arr[idx_max] - xz) > 0.1 for xz in zeros_x)):
            ax_M.plot(x_arr[idx_max], M_ext, 'rs', ms=5)
            anotar(ax_M, x_arr[idx_max], M_ext, f'{M_ext/1000:.2f} kN·m', 'darkred',
                  offset_y=-14 if M_ext >= 0 else 10)

        for xv in [td['x_ini'], td['x_fin']]:
            ax_M.axvline(xv, color='gray', lw=0.5, ls=':')

    ax_M.set_title("Diagrama de Momento Flector (M)", fontsize=10, fontweight='bold')
    ax_M.set_ylabel("M (kN·m)")
    ax_M.yaxis.set_major_formatter(plt.FuncFormatter(lambda v, _: f'{v/1000:.0f}'))
    ax_M.invert_yaxis()
    ax_M.grid(True, alpha=0.4)

    # ══════════════════════════════════════════════════════════════════════════
    # SUBPLOT 5 — DEFLEXIÓN  (sin invert_yaxis: deflexión negativa va hacia abajo)
    # ══════════════════════════════════════════════════════════════════════════
    Def_mm = np.array(Def_total) * 1000
    ax_Def.axhline(0, color='black', lw=0.8, ls='--')
    ax_Def.plot(x_total, Def_mm, 'b', lw=1.5)
    ax_Def.fill_between(x_total, Def_mm, color='blue', alpha=0.15)

    for td in tramos_data:
        Def_arr = np.array(td['Def']) * 1000
        x_arr   = np.array(td['x'])
        # Punto de máxima deflexión hacia abajo (mínimo = más negativo)
        idx_min = np.argmin(Def_arr)
        D_min   = Def_arr[idx_min]
        ax_Def.plot(x_arr[idx_min], D_min, 'bv', ms=6)
        anotar(ax_Def, x_arr[idx_min], D_min,
              f'{D_min:.3f} mm', 'blue', offset_y=-16)

        for xv in [td['x_ini'], td['x_fin']]:
            ax_Def.axvline(xv, color='gray', lw=0.5, ls=':')

    ax_Def.set_title("Diagrama de Deflexión", fontsize=10, fontweight='bold')
    ax_Def.set_ylabel("Deflexión (mm)")
    ax_Def.set_xlabel("Longitud (m)")
    ax_Def.grid(True, alpha=0.4)
    # SIN invert_yaxis: valores negativos quedan abajo (deflexión real hacia abajo)

    plt.savefig("viga_anotada.png", dpi=150, bbox_inches='tight')
    plt.show()
    print("Gráfico guardado como 'viga_anotada.png'")


# --- INPUT DE USUARIO ---
L_tramos   = [2, 3.4, 5.89, 4.345, 6.5]       # Longitudes de tramo (m)
W_tramos   = [12, 15, 12, 20, 15]    # Cargas distribuidas (kN/m)
E_material = 200e9            # Módulo de elasticidad (Pa)
I_seccion  = 0.0005           # Inercia de sección (m⁴)

# Realizar el análisis
results = analizar_viga_final(L_tramos, [w * 1000 for w in W_tramos], E_material, I_seccion)

if results is not None:
    posiciones_apoyos = results['posiciones_apoyos']
    L_total = results['L_total']
    reacciones = results['reacciones']
    tramos_data = results['tramos_data']
    x_total = results['x_total']
    V_total = results['V_total']
    M_total = results['M_total']
    Def_total = results['Def_total']

    # Imprimir fuerzas cortantes y momentos
    print("\n--- RESUMEN DE RESULTADOS ---")
    print("\nReacciones en los apoyos (kN):")
    for i, loc in enumerate(posiciones_apoyos):
        if 2*i < len(reacciones):
            print(f"  Apoyo {i+1} (en x={loc:.2f}m): R = {reacciones[2*i]/1000:.2f} kN")

    print("\nFuerzas Cortantes (V) y Momentos Flectores (M) en cada tramo:")
    for i, td in enumerate(tramos_data):
        print(f"\n  --- Tramo {i+1} (Longitud: {td['L']:.2f} m, Carga: {td['w']/1000:.1f} kN/m) ---")
        V_arr = np.array(td['V'])
        x_arr = np.array(td['x'])
        M_arr = np.array(td['M'])

        # Cortantes en los extremos
        print(f"    V en el inicio (x={td['x_ini']:.2f}m): {V_arr[0]/1000:.2f} kN")
        print(f"    V en el final (x={td['x_fin']:.2f}m): {V_arr[-1]/1000:.2f} kN")
        # Máximo/mínimo cortante en el tramo
        idx_max_V = np.argmax(np.abs(V_arr))
        if 0.05 * len(V_arr) < idx_max_V < 0.95 * len(V_arr):
            V_ext_val = V_arr[idx_max_V]
            V_ext_x = x_arr[idx_max_V]
            print(f"    V Extremo (x={V_ext_x:.2f}m): {V_ext_val/1000:.2f} kN")

        # Momentos en los extremos
        print(f"    M en el inicio (x={td['x_ini']:.2f}m): {M_arr[0]/1000:.2f} kN·m")
        print(f"    M en el final (x={td['x_fin']:.2f}m): {M_arr[-1]/1000:.2f} kN·m")

        # Momentos donde la cortante es cero
        def x_V_cero_local(td_local):
            V_local = np.array(td_local['V'])
            x_local = np.array(td_local['x'])
            crosses = np.where(np.diff(np.sign(V_local)))[0]
            results_local = []
            for c in crosses:
                x0, x1, v0, v1 = x_local[c], x_local[c+1], V_local[c], V_local[c+1]
                xz = x0 - v0 * (x1 - x0) / (v1 - v0)
                idx = np.argmin(np.abs(x_local - xz))
                results_local.append((xz, td_local['M'][idx]))
            return results_local

        for xz, Mz in x_V_cero_local(td):
            print(f"    M donde V=0 (x={xz:.2f}m): {Mz/1000:.2f} kN·m")

        # Máximo/mínimo momento en el tramo
        idx_max_M = np.argmax(np.abs(M_arr))
        M_ext_val = M_arr[idx_max_M]
        M_ext_x = x_arr[idx_max_M]
        zeros_x_for_M = [xz for xz, _ in x_V_cero_local(td)]
        # Only print if it's a true local extremum not already covered by V=0
        if (0.05 * len(M_arr) < idx_max_M < 0.95 * len(M_arr) and
            all(abs(M_ext_x - xz) > 0.01 for xz in zeros_x_for_M)):
            print(f"    M Extremo (x={M_ext_x:.2f}m): {M_ext_val/1000:.2f} kN·m")


    # Generar los gráficos
    plot_beam_results(posiciones_apoyos, L_total, reacciones, tramos_data, x_total, V_total, M_total, Def_total)

